-- chirps schema
--
-- NOTE: evolutions split statements on every ";" -- even inside a comment or string. Keep
-- semicolons out of comments (or escape as ";;") or the statement is cut mid-line.

-- !Ups
create table chirps (
  id bigint generated by default as identity primary key,
  author varchar(15) not null,
  -- 280 is a code-point limit, and surrogate pairs mean up to 2 chars per code point
  body varchar(560) not null,
  created_at timestamp(9) with time zone not null,
  likes int not null default 0
);

create index chirps_author_idx on chirps(author);

-- !Downs
drop index chirps_author_idx;
drop table chirps;
