-- users

-- !Ups
create table users (
  id bigint generated by default as identity primary key,
  handle varchar(15) not null,
  -- bcrypt output is 60 chars, with headroom for a future algorithm tag
  password_hash varchar(100) not null,
  created_at timestamp(9) with time zone not null,
  constraint uq_users_handle unique (handle)
);

-- chirps.author stays a denormalized handle rather than gaining a user_id FK in this step:
-- chirps predating accounts have authors with no user row. Writes now require a session, so
-- every NEW chirp's author is a registered handle. The FK migration is a later evolution.

-- !Downs
drop table users;
