-- tweets (twitter-spring-reactjs port phase 3 core, see PORTING.md)

-- !Ups
create table tweets (
  id bigint generated by default as identity primary key,
  text varchar(560) not null,
  author_id bigint not null,
  created_at timestamp(9) with time zone not null,
  constraint fk_tweets_author foreign key (author_id) references users (id)
);

create index tweets_author_idx on tweets(author_id);

-- !Downs
drop index tweets_author_idx;
drop table tweets;
