-- tweet likes and retweets (twitter-spring-reactjs port, PORTING.md phase 3 interactions)
-- Join tables, not counters: a like is one row per (user, tweet), so a user cannot like twice
-- and the count is always derivable. This also fixes the earlier /api counter's double-like flaw.

-- !Ups
create table tweet_likes (
  id bigint generated by default as identity primary key,
  user_id bigint not null,
  tweet_id bigint not null,
  created_at timestamp(9) with time zone not null,
  constraint fk_tweet_likes_user foreign key (user_id) references users (id),
  constraint fk_tweet_likes_tweet foreign key (tweet_id) references tweets (id) on delete cascade,
  constraint uq_tweet_likes unique (user_id, tweet_id)
);
create index tweet_likes_tweet_idx on tweet_likes(tweet_id);

create table tweet_retweets (
  id bigint generated by default as identity primary key,
  user_id bigint not null,
  tweet_id bigint not null,
  created_at timestamp(9) with time zone not null,
  constraint fk_tweet_retweets_user foreign key (user_id) references users (id),
  constraint fk_tweet_retweets_tweet foreign key (tweet_id) references tweets (id) on delete cascade,
  constraint uq_tweet_retweets unique (user_id, tweet_id)
);
create index tweet_retweets_tweet_idx on tweet_retweets(tweet_id);

-- A reply is a tweet pointing at its parent. Nullable: a top-level tweet has no parent.
alter table tweets add column reply_to_id bigint;
alter table tweets add constraint fk_tweets_reply foreign key (reply_to_id) references tweets (id) on delete cascade;
create index tweets_reply_idx on tweets(reply_to_id);

-- !Downs
drop index tweets_reply_idx;
alter table tweets drop constraint fk_tweets_reply;
alter table tweets drop column reply_to_id;
drop table tweet_retweets;
drop table tweet_likes;
